name: Jekyll Site CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Update Bundler
        run: |
          gem install bundler
          bundle update

      - name: Clear Bundler Cache (if needed)
        run: |
          bundle clean --force || true

      - name: Install dependencies
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Upload site to Pages
        if: success()
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site
